use_frameworks!

platform :ios, '8.0'

target 'MyCategory_Example' do
  pod 'MyCategory', :path => '../'

  target 'MyCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
