use_frameworks!
source 'https://github.com/ZkmlEasycarOrganization/ZkmlRemotePodSpecs.git'
# Cocoapods远程公共库
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MyCategory_Example' do
  pod 'MyCategory', :path => '../'

  target 'MyCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
